### PR TITLE
upgrade tendermint to v0.33.3

### PR DESCRIPTION
**Pull request by cbarraford**
Upgrading `go-sdk` to the latest version of `tendermint`

### CODE REVIEW

**Comment by guagualvcha** [comment]
Thank you for your contribution.  I came across the issue using your branch: 
image
Would you run the test case under `e2e` package? Especially cases in`e2e_rpc_test.go`, since some cases need a private key,  you may change the case a bit.

**Comment by cbarraford** [comment]
@guagualvcha sorry about that. Looks like my editor auto messed with the imports. Fixed now.

**Comment by jackzampolin** [comment]
Would love to help get y'all upgraded to the latest versions of things!

**Comment by guagualvcha** [comment]
> @guagualvcha sorry about that. Looks like my editor auto messed with the imports. Fixed now.

Hi, looks like still can not compile,  https://github.com/cbarraford/go-sdk/blob/70a024137378106032d8c0c7fb89d5f1d42fa37d/client/rpc/types.go#L35  Unresolved type KVPair

**Comment by cbarraford** [comment]
@guagualvcha fixed. Noticed you don't have CI on your PRs. Is that something worth setting up?

**Pull request merged**
